name: "✨ Feature Request"
description: Create a new ticket for a feature request
title: "✨ <title>"
labels: [
  "feature"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
